# Generated by Django 5.1.2 on 2024-10-29 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='work_covers/')),
                ('video', models.URLField(blank=True, null=True)),
                ('date', models.IntegerField()),
                ('image_title', models.CharField(blank=True, max_length=255)),
                ('image_type', models.CharField(choices=[('full', 'Full'), ('half', 'Half')], max_length=10)),
                ('category', models.ManyToManyField(related_name='works', to='services.service')),
                ('contributor', models.ManyToManyField(blank=True, related_name='works', to='works.contributor')),
                ('extra_data', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_extra', to='works.extradata')),
            ],
        ),
        migrations.AddField(
            model_name='extradata',
            name='work',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra_data_relation', to='works.work'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='works.work'),
        ),
    ]
