# Generated by Django 5.1.2 on 2024-10-29 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='image_title',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image_type',
        ),
        migrations.AlterField(
            model_name='work',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='work_videos/'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.ImageField(upload_to='work_images/')),
                ('image_type', models.CharField(choices=[('full', 'Full'), ('half', 'Half')], max_length=10)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='works.work')),
            ],
        ),
    ]
