# Generated by Django 5.1.2 on 2024-10-29 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_remove_work_image_title_remove_work_image_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='work',
        ),
    ]
