# Generated by Django 5.1.2 on 2024-10-29 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_remove_contributor_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='extra_data',
        ),
        migrations.AlterField(
            model_name='extradata',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_data', to='works.work'),
        ),
    ]
