# Generated by Django 5.1.2 on 2024-10-29 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procces', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='desc',
            new_name='description',
        ),
    ]
