# Generated by Django 5.1.2 on 2024-10-29 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='paragraphs',
        ),
        migrations.AddField(
            model_name='paragraph',
            name='blog',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='blog.blog'),
            preserve_default=False,
        ),
    ]
